# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.40-bit-serializer-optimized")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.40-main-packet-header-optimized")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.40-main-packet-tag-optimized")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.40-packet-socket-apps-optimized")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisons "ns3.40-lollipop-comparisons-optimized")
set_tests_properties(ctest-lollipop-comparisons PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/network/examples/CMakeLists.txt;0;")
