# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/src/wifi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wifi-phy-test "ns3.40-wifi-phy-test-optimized")
set_tests_properties(ctest-wifi-phy-test PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;1;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-test-interference-helper "ns3.40-wifi-test-interference-helper-optimized")
set_tests_properties(ctest-wifi-test-interference-helper PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;11;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-manager-example "ns3.40-wifi-manager-example-optimized")
set_tests_properties(ctest-wifi-manager-example PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;21;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-trans-example "ns3.40-wifi-trans-example-optimized")
set_tests_properties(ctest-wifi-trans-example PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;33;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-configuration "ns3.40-wifi-phy-configuration-optimized")
set_tests_properties(ctest-wifi-phy-configuration PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;45;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi "ns3.40-wifi-bianchi-optimized")
set_tests_properties(ctest-wifi-bianchi PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;52;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-he-network-channel-sounding "ns3.40-wifi-he-network-channel-sounding-optimized")
set_tests_properties(ctest-wifi-he-network-channel-sounding PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;61;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/wifi/examples/CMakeLists.txt;0;")
