import re
import numpy as np
import matplotlib.pyplot as plt
from math import factorial

# Sample data string containing "Poisson distribution: X" patterns
data_text = """
Poisson distribution: 97
Poisson distribution: 110
Poisson distribution: 95
Poisson distribution: 78
Poisson distribution: 89
Poisson distribution: 113
Poisson distribution: 92
Poisson distribution: 106
Poisson distribution: 91
Poisson distribution: 98
Poisson distribution: 87
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 108
Poisson distribution: 99
Poisson distribution: 84
Poisson distribution: 106
Poisson distribution: 105
Poisson distribution: 94
Poisson distribution: 85
Poisson distribution: 94
Poisson distribution: 101
Poisson distribution: 106
Poisson distribution: 99
Poisson distribution: 115
Poisson distribution: 90
Poisson distribution: 121
Poisson distribution: 103
Poisson distribution: 94
Poisson distribution: 113
Poisson distribution: 125
Poisson distribution: 98
Poisson distribution: 98
Poisson distribution: 109
Poisson distribution: 84
Poisson distribution: 103
Poisson distribution: 99
Poisson distribution: 89
Poisson distribution: 105
Poisson distribution: 96
Poisson distribution: 117
Poisson distribution: 102
Poisson distribution: 103
Poisson distribution: 110
Poisson distribution: 111
Poisson distribution: 108
Poisson distribution: 109
Poisson distribution: 96
Poisson distribution: 90
Poisson distribution: 120
Poisson distribution: 99
Poisson distribution: 93
Poisson distribution: 96
Poisson distribution: 102
Poisson distribution: 106
Poisson distribution: 92
Poisson distribution: 106
Poisson distribution: 94
Poisson distribution: 118
Poisson distribution: 102
Poisson distribution: 111
Poisson distribution: 104
Poisson distribution: 93
Poisson distribution: 103
Poisson distribution: 103
Poisson distribution: 107
Poisson distribution: 115
Poisson distribution: 110
Poisson distribution: 103
Poisson distribution: 119
Poisson distribution: 101
Poisson distribution: 97
Poisson distribution: 99
Poisson distribution: 112
Poisson distribution: 97
Poisson distribution: 92
Poisson distribution: 104
Poisson distribution: 90
Poisson distribution: 99
Poisson distribution: 85
Poisson distribution: 114
Poisson distribution: 98
Poisson distribution: 88
Poisson distribution: 79
Poisson distribution: 100
Poisson distribution: 98
Poisson distribution: 99
Poisson distribution: 115
Poisson distribution: 98
Poisson distribution: 105
Poisson distribution: 118
Poisson distribution: 104
Poisson distribution: 95
Poisson distribution: 111
Poisson distribution: 86
Poisson distribution: 102
Poisson distribution: 95
Poisson distribution: 106
Poisson distribution: 106
Poisson distribution: 105
Poisson distribution: 102
Poisson distribution: 97
Poisson distribution: 93
Poisson distribution: 120
Poisson distribution: 93
Poisson distribution: 78
Poisson distribution: 114
Poisson distribution: 104
Poisson distribution: 106
Poisson distribution: 100
Poisson distribution: 113
Poisson distribution: 94
Poisson distribution: 114
Poisson distribution: 100
Poisson distribution: 104
Poisson distribution: 87
Poisson distribution: 105
Poisson distribution: 94
Poisson distribution: 128
Poisson distribution: 103
Poisson distribution: 99
Poisson distribution: 72
Poisson distribution: 100
Poisson distribution: 94
Poisson distribution: 104
Poisson distribution: 97
Poisson distribution: 97
Poisson distribution: 109
Poisson distribution: 106
Poisson distribution: 95
Poisson distribution: 91
Poisson distribution: 93
Poisson distribution: 88
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 91
Poisson distribution: 96
Poisson distribution: 96
Poisson distribution: 78
Poisson distribution: 97
Poisson distribution: 114
Poisson distribution: 102
Poisson distribution: 88
Poisson distribution: 120
Poisson distribution: 98
Poisson distribution: 100
Poisson distribution: 99
Poisson distribution: 85
Poisson distribution: 107
Poisson distribution: 107
Poisson distribution: 84
Poisson distribution: 99
Poisson distribution: 114
Poisson distribution: 107
Poisson distribution: 108
Poisson distribution: 93
Poisson distribution: 85
Poisson distribution: 111
Poisson distribution: 105
Poisson distribution: 96
Poisson distribution: 99
Poisson distribution: 111
Poisson distribution: 103
Poisson distribution: 83
Poisson distribution: 111
Poisson distribution: 100
Poisson distribution: 108
Poisson distribution: 92
Poisson distribution: 101
Poisson distribution: 117
Poisson distribution: 109
Poisson distribution: 97
Poisson distribution: 98
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 86
Poisson distribution: 99
Poisson distribution: 104
Poisson distribution: 81
Poisson distribution: 106
Poisson distribution: 93
Poisson distribution: 112
Poisson distribution: 127
Poisson distribution: 124
Poisson distribution: 82
Poisson distribution: 92
Poisson distribution: 87
Poisson distribution: 93
Poisson distribution: 117
Poisson distribution: 112
Poisson distribution: 98
Poisson distribution: 95
Poisson distribution: 96
Poisson distribution: 103
Poisson distribution: 102
Poisson distribution: 84
Poisson distribution: 101
Poisson distribution: 113
Poisson distribution: 105
Poisson distribution: 96
Poisson distribution: 106
Poisson distribution: 93
Poisson distribution: 109
Poisson distribution: 95
Poisson distribution: 79
Poisson distribution: 97
Poisson distribution: 93
Poisson distribution: 114
Poisson distribution: 122
Poisson distribution: 106
Poisson distribution: 112
Poisson distribution: 112
Poisson distribution: 95
Poisson distribution: 94
Poisson distribution: 101
Poisson distribution: 88
Poisson distribution: 97
Poisson distribution: 96
Poisson distribution: 116
Poisson distribution: 100
Poisson distribution: 101
Poisson distribution: 109
Poisson distribution: 130
Poisson distribution: 95
Poisson distribution: 101
Poisson distribution: 97
Poisson distribution: 111
Poisson distribution: 94
Poisson distribution: 98
Poisson distribution: 92
Poisson distribution: 94
Poisson distribution: 94
Poisson distribution: 113
Poisson distribution: 99
Poisson distribution: 106
Poisson distribution: 97
Poisson distribution: 108
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 104
Poisson distribution: 101
Poisson distribution: 105
Poisson distribution: 105
Poisson distribution: 91
Poisson distribution: 90
Poisson distribution: 109
Poisson distribution: 95
Poisson distribution: 94
Poisson distribution: 102
Poisson distribution: 115
Poisson distribution: 111
Poisson distribution: 102
Poisson distribution: 101
Poisson distribution: 115
Poisson distribution: 99
Poisson distribution: 94
Poisson distribution: 103
Poisson distribution: 87
Poisson distribution: 93
Poisson distribution: 102
Poisson distribution: 89
Poisson distribution: 88
Poisson distribution: 109
Poisson distribution: 109
Poisson distribution: 103
Poisson distribution: 116
Poisson distribution: 101
Poisson distribution: 112
Poisson distribution: 93
Poisson distribution: 111
Poisson distribution: 109
Poisson distribution: 90
Poisson distribution: 101
Poisson distribution: 82
Poisson distribution: 91
Poisson distribution: 97
Poisson distribution: 97
Poisson distribution: 102
Poisson distribution: 97
Poisson distribution: 105
Poisson distribution: 81
Poisson distribution: 88
Poisson distribution: 100
Poisson distribution: 105
Poisson distribution: 94
Poisson distribution: 98
Poisson distribution: 102
Poisson distribution: 117
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 91
Poisson distribution: 94
Poisson distribution: 114
Poisson distribution: 127
Poisson distribution: 85
Poisson distribution: 106
Poisson distribution: 107
Poisson distribution: 98
Poisson distribution: 111
Poisson distribution: 101
Poisson distribution: 93
Poisson distribution: 113
Poisson distribution: 96
Poisson distribution: 98
Poisson distribution: 118
Poisson distribution: 87
Poisson distribution: 97
Poisson distribution: 107
Poisson distribution: 100
Poisson distribution: 97
Poisson distribution: 89
Poisson distribution: 86
Poisson distribution: 91
Poisson distribution: 82
Poisson distribution: 111
Poisson distribution: 96
Poisson distribution: 118
Poisson distribution: 104
Poisson distribution: 103
Poisson distribution: 103
Poisson distribution: 70
Poisson distribution: 110
Poisson distribution: 99
Poisson distribution: 85
Poisson distribution: 89
Poisson distribution: 84
Poisson distribution: 104
Poisson distribution: 90
Poisson distribution: 117
Poisson distribution: 102
Poisson distribution: 90
Poisson distribution: 107
Poisson distribution: 118
Poisson distribution: 94
Poisson distribution: 95
Poisson distribution: 93
Poisson distribution: 104
Poisson distribution: 103
Poisson distribution: 100
Poisson distribution: 90
Poisson distribution: 108
Poisson distribution: 89
Poisson distribution: 98
Poisson distribution: 94
Poisson distribution: 91
Poisson distribution: 89
Poisson distribution: 114
Poisson distribution: 106
Poisson distribution: 93
Poisson distribution: 115
Poisson distribution: 107
Poisson distribution: 97
Poisson distribution: 114
Poisson distribution: 87
Poisson distribution: 93
Poisson distribution: 101
Poisson distribution: 105
Poisson distribution: 101
Poisson distribution: 81
Poisson distribution: 95
Poisson distribution: 95
Poisson distribution: 96
Poisson distribution: 89
Poisson distribution: 118
Poisson distribution: 109
Poisson distribution: 104
Poisson distribution: 94
Poisson distribution: 92
Poisson distribution: 91
Poisson distribution: 100
Poisson distribution: 78
Poisson distribution: 131
Poisson distribution: 107
Poisson distribution: 102
Poisson distribution: 112
Poisson distribution: 99
Poisson distribution: 88
Poisson distribution: 99
Poisson distribution: 84
Poisson distribution: 110
Poisson distribution: 93
Poisson distribution: 111
Poisson distribution: 89
Poisson distribution: 94
Poisson distribution: 94
Poisson distribution: 93
Poisson distribution: 96
Poisson distribution: 102
Poisson distribution: 113
Poisson distribution: 100
Poisson distribution: 116
Poisson distribution: 91
Poisson distribution: 99
Poisson distribution: 117
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 92
Poisson distribution: 107
Poisson distribution: 117
Poisson distribution: 113
Poisson distribution: 98
Poisson distribution: 96
Poisson distribution: 122
Poisson distribution: 125
Poisson distribution: 98
Poisson distribution: 95
Poisson distribution: 113
Poisson distribution: 96
Poisson distribution: 97
Poisson distribution: 91
Poisson distribution: 90
Poisson distribution: 94
Poisson distribution: 98
Poisson distribution: 121
Poisson distribution: 81
Poisson distribution: 103
Poisson distribution: 109
Poisson distribution: 114
Poisson distribution: 84
Poisson distribution: 110
Poisson distribution: 109
Poisson distribution: 114
Poisson distribution: 107
Poisson distribution: 111
Poisson distribution: 110
Poisson distribution: 93
Poisson distribution: 88
Poisson distribution: 108
Poisson distribution: 108
Poisson distribution: 107
Poisson distribution: 97
Poisson distribution: 108
Poisson distribution: 107
Poisson distribution: 96
Poisson distribution: 105
Poisson distribution: 90
Poisson distribution: 98
Poisson distribution: 87
Poisson distribution: 98
Poisson distribution: 92
Poisson distribution: 90
Poisson distribution: 117
Poisson distribution: 103
Poisson distribution: 106
Poisson distribution: 97
Poisson distribution: 115
Poisson distribution: 115
Poisson distribution: 91
Poisson distribution: 74
Poisson distribution: 104
Poisson distribution: 96
Poisson distribution: 89
Poisson distribution: 95
Poisson distribution: 93
Poisson distribution: 104
Poisson distribution: 108
Poisson distribution: 103
Poisson distribution: 106
Poisson distribution: 116
Poisson distribution: 88
Poisson distribution: 112
Poisson distribution: 96
Poisson distribution: 82
Poisson distribution: 103
Poisson distribution: 108
Poisson distribution: 91
Poisson distribution: 106
Poisson distribution: 92
Poisson distribution: 96
Poisson distribution: 113
Poisson distribution: 94
Poisson distribution: 95
Poisson distribution: 71
Poisson distribution: 112
Poisson distribution: 100
Poisson distribution: 113
Poisson distribution: 88
Poisson distribution: 107
Poisson distribution: 106
Poisson distribution: 95
Poisson distribution: 103
Poisson distribution: 99
Poisson distribution: 95
Poisson distribution: 110
Poisson distribution: 85
Poisson distribution: 117
Poisson distribution: 83
Poisson distribution: 108
Poisson distribution: 87
Poisson distribution: 111
Poisson distribution: 88
Poisson distribution: 116
Poisson distribution: 77
Poisson distribution: 107
Poisson distribution: 81
Poisson distribution: 97
Poisson distribution: 118
Poisson distribution: 120
Poisson distribution: 98
Poisson distribution: 78
Poisson distribution: 95
Poisson distribution: 104
Poisson distribution: 111
Poisson distribution: 114
Poisson distribution: 104
Poisson distribution: 92
Poisson distribution: 105
Poisson distribution: 107
Poisson distribution: 112
Poisson distribution: 97
Poisson distribution: 125
Poisson distribution: 116
Poisson distribution: 108
Poisson distribution: 123
Poisson distribution: 92
Poisson distribution: 94
Poisson distribution: 106
Poisson distribution: 90
Poisson distribution: 92
Poisson distribution: 102
Poisson distribution: 92
Poisson distribution: 104
Poisson distribution: 92
Poisson distribution: 98
Poisson distribution: 93
Poisson distribution: 109
Poisson distribution: 97
Poisson distribution: 97
Poisson distribution: 100
Poisson distribution: 99
Poisson distribution: 109
Poisson distribution: 123
Poisson distribution: 104
Poisson distribution: 80
Poisson distribution: 112
Poisson distribution: 88
Poisson distribution: 121
Poisson distribution: 92
Poisson distribution: 120
Poisson distribution: 106
Poisson distribution: 93
Poisson distribution: 99
Poisson distribution: 117
Poisson distribution: 90
Poisson distribution: 88
Poisson distribution: 101
Poisson distribution: 99
Poisson distribution: 116
Poisson distribution: 105
Poisson distribution: 103
Poisson distribution: 109
Poisson distribution: 97
Poisson distribution: 97
Poisson distribution: 106
Poisson distribution: 109
Poisson distribution: 99
Poisson distribution: 106
Poisson distribution: 106
Poisson distribution: 117
Poisson distribution: 102
Poisson distribution: 95
Poisson distribution: 112
Poisson distribution: 92
Poisson distribution: 82
Poisson distribution: 90
Poisson distribution: 85
Poisson distribution: 103
Poisson distribution: 93
Poisson distribution: 109
Poisson distribution: 117
Poisson distribution: 104
Poisson distribution: 116
Poisson distribution: 99
Poisson distribution: 104
Poisson distribution: 108
Poisson distribution: 101
Poisson distribution: 102
Poisson distribution: 95
Poisson distribution: 100
Poisson distribution: 109
Poisson distribution: 103
Poisson distribution: 106
Poisson distribution: 106
Poisson distribution: 97
Poisson distribution: 101
Poisson distribution: 84
Poisson distribution: 94
Poisson distribution: 100
Poisson distribution: 99
Poisson distribution: 90
Poisson distribution: 121
Poisson distribution: 95
Poisson distribution: 91
Poisson distribution: 96
Poisson distribution: 108
Poisson distribution: 110
Poisson distribution: 106
Poisson distribution: 95
Poisson distribution: 90
Poisson distribution: 96
Poisson distribution: 110
Poisson distribution: 102
Poisson distribution: 91
Poisson distribution: 77
Poisson distribution: 91
Poisson distribution: 103
Poisson distribution: 98
Poisson distribution: 95
Poisson distribution: 98
Poisson distribution: 94
Poisson distribution: 104
Poisson distribution: 112
Poisson distribution: 86
Poisson distribution: 96
Poisson distribution: 102
Poisson distribution: 87
Poisson distribution: 110
Poisson distribution: 96
Poisson distribution: 93
Poisson distribution: 106
Poisson distribution: 91
Poisson distribution: 101
Poisson distribution: 101
Poisson distribution: 105
Poisson distribution: 103
Poisson distribution: 104
Poisson distribution: 98
Poisson distribution: 96
Poisson distribution: 99
Poisson distribution: 99
Poisson distribution: 105
Poisson distribution: 102
Poisson distribution: 111
Poisson distribution: 97
Poisson distribution: 106
Poisson distribution: 103
Poisson distribution: 92
Poisson distribution: 107
Poisson distribution: 97
Poisson distribution: 108
Poisson distribution: 101
Poisson distribution: 118
Poisson distribution: 106
Poisson distribution: 94
Poisson distribution: 109
Poisson distribution: 94
Poisson distribution: 83
Poisson distribution: 93
Poisson distribution: 109
Poisson distribution: 106
Poisson distribution: 115
Poisson distribution: 96
Poisson distribution: 99
Poisson distribution: 89
Poisson distribution: 111
Poisson distribution: 105
Poisson distribution: 98
Poisson distribution: 85
Poisson distribution: 101
Poisson distribution: 93
Poisson distribution: 98
Poisson distribution: 82
Poisson distribution: 91
Poisson distribution: 105
Poisson distribution: 105
Poisson distribution: 105
Poisson distribution: 110
Poisson distribution: 105
Poisson distribution: 105
Poisson distribution: 102
Poisson distribution: 98
Poisson distribution: 97
Poisson distribution: 85
Poisson distribution: 87
Poisson distribution: 113
Poisson distribution: 97
Poisson distribution: 115
Poisson distribution: 84
Poisson distribution: 102
Poisson distribution: 96
Poisson distribution: 111
Poisson distribution: 88
Poisson distribution: 101
Poisson distribution: 93
Poisson distribution: 110
Poisson distribution: 102
Poisson distribution: 110
Poisson distribution: 105
Poisson distribution: 117
Poisson distribution: 107
Poisson distribution: 109
Poisson distribution: 81
Poisson distribution: 78
Poisson distribution: 98
Poisson distribution: 106
Poisson distribution: 88
Poisson distribution: 89
Poisson distribution: 107
Poisson distribution: 89
Poisson distribution: 99
Poisson distribution: 123
Poisson distribution: 103
Poisson distribution: 99
Poisson distribution: 120
Poisson distribution: 98
Poisson distribution: 110
Poisson distribution: 106
Poisson distribution: 98
Poisson distribution: 106
Poisson distribution: 107
Poisson distribution: 101
Poisson distribution: 109
Poisson distribution: 105
Poisson distribution: 86
Poisson distribution: 112
Poisson distribution: 103
Poisson distribution: 109
Poisson distribution: 97
Poisson distribution: 99
Poisson distribution: 94
Poisson distribution: 108
Poisson distribution: 87
Poisson distribution: 107
Poisson distribution: 112
Poisson distribution: 93
Poisson distribution: 116
Poisson distribution: 113
Poisson distribution: 98
Poisson distribution: 93
Poisson distribution: 117
Poisson distribution: 95
Poisson distribution: 100
Poisson distribution: 97
Poisson distribution: 105
Poisson distribution: 117
Poisson distribution: 99
Poisson distribution: 94
Poisson distribution: 95
Poisson distribution: 104
Poisson distribution: 97
Poisson distribution: 105
Poisson distribution: 119
Poisson distribution: 102
Poisson distribution: 99
Poisson distribution: 105
Poisson distribution: 97
Poisson distribution: 100
Poisson distribution: 104
Poisson distribution: 106
Poisson distribution: 107
Poisson distribution: 117
Poisson distribution: 111
Poisson distribution: 111
Poisson distribution: 78
Poisson distribution: 91
Poisson distribution: 96
Poisson distribution: 107
Poisson distribution: 85
Poisson distribution: 102
Poisson distribution: 105
Poisson distribution: 106
Poisson distribution: 105
Poisson distribution: 85
Poisson distribution: 119
Poisson distribution: 74
Poisson distribution: 79
Poisson distribution: 119
Poisson distribution: 116
Poisson distribution: 86
Poisson distribution: 98
Poisson distribution: 102
Poisson distribution: 108
Poisson distribution: 97
Poisson distribution: 89
Poisson distribution: 115
Poisson distribution: 112
Poisson distribution: 91
Poisson distribution: 88
Poisson distribution: 87
Poisson distribution: 96
Poisson distribution: 102
Poisson distribution: 88
Poisson distribution: 94
Poisson distribution: 111
Poisson distribution: 110
Poisson distribution: 109
Poisson distribution: 94
Poisson distribution: 90
Poisson distribution: 109
Poisson distribution: 106
Poisson distribution: 117
Poisson distribution: 118
Poisson distribution: 102
Poisson distribution: 86
Poisson distribution: 99
Poisson distribution: 113
Poisson distribution: 107
Poisson distribution: 93
Poisson distribution: 111
Poisson distribution: 83
Poisson distribution: 96
Poisson distribution: 125
Poisson distribution: 88
Poisson distribution: 98
Poisson distribution: 87
Poisson distribution: 110
Poisson distribution: 96
Poisson distribution: 94
Poisson distribution: 105
Poisson distribution: 90
Poisson distribution: 85
Poisson distribution: 96
Poisson distribution: 106
Poisson distribution: 105
Poisson distribution: 112
Poisson distribution: 102
Poisson distribution: 110
Poisson distribution: 105
Poisson distribution: 94
Poisson distribution: 99
Poisson distribution: 94
Poisson distribution: 84
Poisson distribution: 106
Poisson distribution: 96
Poisson distribution: 107
Poisson distribution: 96
Poisson distribution: 93
Poisson distribution: 102
Poisson distribution: 104
Poisson distribution: 88
Poisson distribution: 87
Poisson distribution: 97
Poisson distribution: 117
Poisson distribution: 83
Poisson distribution: 103
Poisson distribution: 106
Poisson distribution: 95
Poisson distribution: 118
Poisson distribution: 115
Poisson distribution: 93
Poisson distribution: 102
Poisson distribution: 91
Poisson distribution: 100
Poisson distribution: 88
Poisson distribution: 100
Poisson distribution: 88
Poisson distribution: 108
Poisson distribution: 109
Poisson distribution: 103
Poisson distribution: 115
Poisson distribution: 89
Poisson distribution: 88
Poisson distribution: 100
Poisson distribution: 111
Poisson distribution: 94
Poisson distribution: 104
Poisson distribution: 112
Poisson distribution: 110
Poisson distribution: 104
Poisson distribution: 100
Poisson distribution: 99
Poisson distribution: 104
Poisson distribution: 93
Poisson distribution: 95
Poisson distribution: 90
Poisson distribution: 103
Poisson distribution: 100
Poisson distribution: 95
Poisson distribution: 106
Poisson distribution: 119
Poisson distribution: 100
Poisson distribution: 100
Poisson distribution: 86
Poisson distribution: 98
Poisson distribution: 92
Poisson distribution: 107
Poisson distribution: 95
Poisson distribution: 98
Poisson distribution: 101
Poisson distribution: 106
Poisson distribution: 103
Poisson distribution: 83
Poisson distribution: 102
Poisson distribution: 106
Poisson distribution: 102
Poisson distribution: 102
Poisson distribution: 86
Poisson distribution: 123
Poisson distribution: 118
Poisson distribution: 100
Poisson distribution: 120
Poisson distribution: 103
Poisson distribution: 100
Poisson distribution: 94
Poisson distribution: 104
Poisson distribution: 98
Poisson distribution: 96
Poisson distribution: 99
Poisson distribution: 100
Poisson distribution: 91
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 84
Poisson distribution: 84
Poisson distribution: 91
Poisson distribution: 92
Poisson distribution: 117
Poisson distribution: 96
Poisson distribution: 121
Poisson distribution: 95
Poisson distribution: 86
Poisson distribution: 106
Poisson distribution: 99
Poisson distribution: 95
Poisson distribution: 109
Poisson distribution: 105
Poisson distribution: 109
Poisson distribution: 110
Poisson distribution: 105
Poisson distribution: 124
Poisson distribution: 98
Poisson distribution: 96
Poisson distribution: 114
Poisson distribution: 98
Poisson distribution: 99
Poisson distribution: 96
Poisson distribution: 89
Poisson distribution: 110
Poisson distribution: 97
Poisson distribution: 95
Poisson distribution: 106
Poisson distribution: 89
Poisson distribution: 89
Poisson distribution: 106
Poisson distribution: 87
Poisson distribution: 99
Poisson distribution: 113
Poisson distribution: 102
Poisson distribution: 95
Poisson distribution: 114
Poisson distribution: 119
Poisson distribution: 85
Poisson distribution: 108
Poisson distribution: 90
Poisson distribution: 112
Poisson distribution: 102
Poisson distribution: 100
Poisson distribution: 97
Poisson distribution: 103
Poisson distribution: 92
Poisson distribution: 98
Poisson distribution: 82
Poisson distribution: 93
Poisson distribution: 104
Poisson distribution: 110
Poisson distribution: 104
Poisson distribution: 129
Poisson distribution: 93
Poisson distribution: 114
Poisson distribution: 78
Poisson distribution: 102
Poisson distribution: 110
Poisson distribution: 106
Poisson distribution: 71
Poisson distribution: 104
Poisson distribution: 99
Poisson distribution: 95
Poisson distribution: 108
Poisson distribution: 113
Poisson distribution: 84
Poisson distribution: 88
Poisson distribution: 104
Poisson distribution: 110
Poisson distribution: 100
Poisson distribution: 97
Poisson distribution: 96
Poisson distribution: 103
Poisson distribution: 115
Poisson distribution: 98
Poisson distribution: 77
Poisson distribution: 103
Poisson distribution: 99
Poisson distribution: 96
Poisson distribution: 100
Poisson distribution: 95
Poisson distribution: 96
Poisson distribution: 116
Poisson distribution: 87
Poisson distribution: 111
Poisson distribution: 74"""

# Extract all the numbers following "Poisson distribution:"
numbers = re.findall(r'Poisson distribution: (\d+)', data_text)

# Convert the extracted numbers to integers
poisson_values = np.array([int(num) for num in numbers])

# Calculate variance and mean of the Poisson values
variance = np.var(poisson_values)
mean = np.mean(poisson_values)

# Unique values and their frequencies for plotting the Poisson PMF
unique_values, counts = np.unique(poisson_values, return_counts=True)
pmf = [(mean**k * np.exp(-mean)) / factorial(k) for k in unique_values]

# Scale the PMF to the number of observations for comparison
pmf_scaled = np.array(pmf) * len(poisson_values)

# Plot the histogram of the Poisson values
plt.figure(figsize=(10, 6))
plt.hist(poisson_values, bins=range(int(min(poisson_values)), int(max(poisson_values)+2)), 
                 edgecolor='black', alpha=0.7, density=True, label='Data Histogram')

# Plot the Poisson distribution curve (PMF)
plt.plot(unique_values, pmf_scaled / len(poisson_values), 'r-', lw=2, label=f'Poisson PMF\nMean: {mean:.2f}')  # Normalize PMF

# Customize plot
plt.title('Poisson Data Distribution with Poisson Curve')
plt.xlabel('Value')
plt.ylabel('Density')
plt.grid(True)
plt.legend()

# Show the plot and print the variance
plt.show()

print(f"Variance of Poisson values: {variance}")

