# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3.40-dumbbell-animation-optimized")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3.40-grid-animation-optimized")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3.40-star-animation-optimized")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3.40-colors-link-description-optimized")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3.40-resources-counters-optimized")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3.40-wireless-animation-optimized")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3.40-uan-animation-optimized")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/netanim/examples/CMakeLists.txt;0;")
