# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/src/buildings/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-buildings-pathloss-profiler "ns3.40-buildings-pathloss-profiler-optimized")
set_tests_properties(ctest-buildings-pathloss-profiler PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;1;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-group-mobility-example "ns3.40-outdoor-group-mobility-example-optimized")
set_tests_properties(ctest-outdoor-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;11;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-random-walk-example "ns3.40-outdoor-random-walk-example-optimized")
set_tests_properties(ctest-outdoor-random-walk-example PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;17;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/buildings/examples/CMakeLists.txt;0;")
