# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3.40-socket-bound-static-routing-optimized")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/examples/socket/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;1;build_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3.40-socket-bound-tcp-static-routing-optimized")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/examples/socket/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;11;build_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3.40-socket-options-ipv4-optimized")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/examples/socket/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;22;build_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3.40-socket-options-ipv6-optimized")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/examples/socket/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;32;build_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/examples/socket/CMakeLists.txt;0;")
