# CMake generated Testfile for 
# Source directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/olsr/examples
# Build directory: /home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/cmake-cache/src/olsr/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-olsr-hna "ns3.40-olsr-hna-optimized")
set_tests_properties(ctest-olsr-hna PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/olsr/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/olsr/examples/CMakeLists.txt;1;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/olsr/examples/CMakeLists.txt;0;")
add_test(ctest-simple-point-to-point-olsr "ns3.40-simple-point-to-point-olsr-optimized")
set_tests_properties(ctest-simple-point-to-point-olsr PROPERTIES  WORKING_DIRECTORY "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build/src/olsr/examples/" _BACKTRACE_TRIPLES "/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/olsr/examples/CMakeLists.txt;12;build_lib_example;/home/idomanuel/workspace3.40pure_cobakan/ns-3-allinone/ns-3.40/src/olsr/examples/CMakeLists.txt;0;")
